name: ai_dev_${UNIQUE_PROJECT_NAME:?Set UNIQUE_PROJECT_NAME in .devcontainer/ai_dev_container/.env, must be lowercase and no spaces}

include:
  - ../../agentic_tools/mcp/compose.mcp-gateway.yml

services:
  ai_dev_user:
    build:
      context: .
      dockerfile: ./Dockerfile.user
      args:
        USERNAME: human_user
        USER_UID: 43927
        USER_GID: 43927
    # for human_user
    user: "43927:43927"
    working_dir: /workspace

    volumes:
      - type: bind
        source: ../../.
        target: /workspace
        read_only: false

      - type: volume
        source: ai_dev_user_home
        target: /home/human_user

  ai_dev_agent:
    extends:
      file: compose.ai-dev-sandbox.yml
      service: ai_dev_sandbox
    build:
      context: .
      dockerfile: ./Dockerfile.agent
      args:
        USERNAME: agent
        USER_UID: 43927
        USER_GID: 43927

    volumes:
      - type: volume
        source: ai_dev_agent_home
        target: /home/agent

volumes:
  ai_dev_agent_home:
  ai_dev_user_home: