# syntax=docker/dockerfile:1

# BASE_IMAGE must be Debian/Ubuntu images
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG USERNAME=agent
ARG USER_UID=43927
ARG USER_GID=43927

USER root

RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
    && useradd \
        --uid "${USER_UID}" \
        --gid "${USER_GID}" \
        --create-home \
        --shell /bin/bash \
        "${USERNAME}" \
    && mkdir -p \
        /workspace \
        /home/${USERNAME}/.vscode-server \
        /home/${USERNAME}/.cache \
    && chown -R "${USER_UID}:${USER_GID}" \
        /workspace \
        /home/${USERNAME}

# make sure git is installed
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/*

# mark /workspace as safe, so version control will work inside devcontainer
RUN git config --system --add safe.directory /workspace

USER ${USERNAME}

ENV HOME=/home/${USERNAME}

WORKDIR /workspace

CMD ["sleep", "infinity"]