ARG YQ_VERSION=4.52.5

FROM mikefarah/yq:${YQ_VERSION} AS yq

FROM debian:bookworm-slim

USER root

# currently bubblewrap doesn't work, I will leave it here
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        git \
        jq \
        less \
        procps \
        ripgrep \
        unzip \
        bubblewrap \
        nodejs \
        npm \
    && rm -rf /var/lib/apt/lists/*

COPY --from=yq /usr/bin/yq /usr/local/bin/yq

CMD ["sleep", "infinity"]