ARG YQ_VERSION=4.52.5
ARG NODE_VERSION=22-bookworm-slim

FROM mikefarah/yq:${YQ_VERSION} AS yq

FROM node:${NODE_VERSION}

USER root

# install some relevant stuff
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        git \
        jq \
        less \
        procps \
        ripgrep \
        unzip \
        bubblewrap \
        python3 \
        python3-yaml \
        file \
        shellcheck \
    && rm -rf /var/lib/apt/lists/*

# not sure if i will ever need yq again... i will leave ith ere
COPY --from=yq /usr/bin/yq /usr/local/bin/yq

# install codex cli
RUN npm install --global @openai/codex@0.147.0

CMD ["sleep", "infinity"]