name: ai_dev_${UNIQUE_PROJECT_NAME:?Set UNIQUE_PROJECT_NAME in .env, must be lowercase and no spaces}

include:
  - compose.ai-dev-project-bridge.yml

services:
  ai_dev_with_project:
    extends:
      file: compose.ai-dev-common.yml
      service: ai_dev_common
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile.ai-dev
      args:
        BASE_IMAGE: "ai_dev_${UNIQUE_PROJECT_NAME:?Error}-${PROJECT_LOCAL_DEV_SERVICE:?Set PROJECT_LOCAL_DEV_SERVICE in .env}:latest"
        USERNAME: agent
        USER_UID: 43927
        USER_GID: 43927

    volumes:
      - type: volume
        source: ai_dev_with_project_home
        target: /home/agent
        read_only: false

volumes:
  ai_dev_with_project_home: